spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rv?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
      database: 1
  mail:
    host: smtp.qq.com
    port: 587
    username: 2912528586@qq.com
    password: zjaxvmblvcuedhag
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  #将参数以时间戳返回
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    static-path-pattern: /images/**
  web:
    resources:
      static-locations: file:${user.dir}/src/main/resources/static/
#上传文件路径
uploadFilePath:
  campgroundPicturesPath: ${user.dir}/src/main/resources/static/campgroundPictures
  vehiclePicturesPath: ${user.dir}/src/main/resources/static/vehiclePictures


mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8888

